apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  selector:
    matchLabels:
      app: api-produto
  replicas: 2
  template:
    metadata:
      labels:
        app: api-produto
    spec:
      containers:
      - name: api-produto
        image: samukamaciel/kubebootcamp-aula02
        ports:
        - containerPort: 8080
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
