apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  selector:
    matchLabels:
      app: api-produto
  replicas: 5
  template:
    metadata:
      labels:
        app: api-produto
    spec:
      containers:
      - name: api-produto
        image: samukamaciel/kubebootcamp-aula02
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            port: 8080
            path: /read
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
